name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # deploy when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/sadansabo/deforestation-agent-dashboard
          git push space main --force
